version: '3.1'

services:
  web:
    image: python:3.8
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
       sh -c "apt-get update &&
             apt-get install -y libfaketime &&
             pip install -r /app/requirements.txt &&
             python /app/app.py"
    user: root
  #  #  export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1 &&
            #  export FAKETIME='-15h' &&

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: